[flavor]
dark = "ayu-dark"

[mgr]
border_symbol = " "

[tabs]
active   = { bg = "#fbaed2", bold = true }
inactive = { fg = "#fbaed2", bg = "white", bold = true }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

[confirm]
border = { fg = "#fbaed2" }
title = { fg = "#fbaed2" }

[spot]
border = { fg = "#fbaed2" }
title = { fg = "#fbaed2" }
tab_col = { fg = "#fbaed2" }
